# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('bio', tinymce.models.HTMLField()),
                ('contact', models.CharField(max_length=12)),
                ('linkedIn', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awards.User')),
            ],
        ),
    ]
